# -*- coding: utf-8 -*-

"""
Anki Add-on: Anki Contextualize

Please do not edit this file unless you know what you are doing.

Copyright: (c) 2019 Henrik Giesel <https://glutanimate.com/>
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl.html>
"""

from . import context
