= Anki Plus Archive

==== The problem

Anki is a SRS software that helps you remember knowledge
with the least effort possible.
The best Anki cards are built with the
link:https://supermemo.guru/wiki/20_rules_of_knowledge_formulation[*minimum information principle*]
in mind.
For vocabulary of a foreign language, this means you don't
require the knowledge of other words in order to guess the
content of the current card. By adding example sentences,
you can create some context, but besides that you generally
strife for minimal interference between cards.

However most other knowledge is settled in a lot of context.
For example, knowing what web sites are, is inseparably
connected to what HTTP requests are, what HTML looks like, etc.

Thinkable ways to create learn such content with Anki include:

* creating _big notes, that contain all of the information_ on one note

However this violates the aforementioned *minimum information principle*

* creating _small notes, but a lot of them_

This is the desirable solution. Individual notes concerning a topic can be connected with tags.
However, while Anki is an ideal solution for you spaced repetition needs,
it does not work well as a general archive for your knowledge.
For example, it is neither easy to browse, or edit existing cards.
Another issue that you cannot easliy add sources,
or information to a multiple of notes, as the information always has
to be associated with an individual card. And last but not least,
adding information requires you to create a note for it. However
there might be information associated with a note in Anki,
which does not need to be a note itself or part of the note.

==== The solution

This addon is a tool suite to help you create two-way
connections between Anki with your digital note archive.
It assumes you have text files written in plain text, which
contain content you want to add as notes to your Anki deck.
They might be written in plain text formats, including
link:https://en.wikipedia.org/wiki/Markdown[Markdown],
link:https://asciidoctor.org/docs/what-is-asciidoc[Asciidoc] (my recommendation!), or
link:https://orgmode.org/[Emacs org-mode].

.It does so in mainly two ways:
. allows you to create buttons in the Anki editor and define commands
. offers the command-line tool `ark`

== For more information, see here

. For more about the command line tool, link:docs/tutorial-ark.adoc[see here]
. For more about the different kinds of ids, link:docs/tutorial-ids.adoc[see here]
. For more about connecting to Anki, link:docs/tutorial-anki.adoc[see here]
. For more about pagerefs, and tocs, link:docs/tutorial-pagerefs[see here]
. For more about the assets directory and assetrefs, link:docs/tutorial-assetrefs.adoc[see here]
. For more about the Anki config file, link:docs/tutorial-config-file.adoc[see here]

== Prerequisities

This addon requires multiple other Anki addons to be installed and needs some
technological know-how on the side of the user. The required addons include

.Necessary add-ons
. link:https://ankiweb.net/shared/info/2055492159[AnkiConnect]
// TODO Add full note id

.Advised add-ons
. link:https://ankiweb.net/shared/info/1642550423[Refocus card when reviewing]

== Setup

// TODO
// Install from Ankiweb
// Setup config file
// Setup a fitting archive
// Test out ark command
// // Install a fitting outside tool (like vim-arkify)
