= Section, page, and quest identifiers

=== Section identifiers

Section identifiers can either signify an individual section, or a section group
a section corresponds to a directory in the filesystem, and contains possible pages.
A section cannot contain another section.
It is marked by containing a `README` file.

Section identifers have the form:

.Section identifier
----
[ancestor//][section]
----

=== Page identifiers

Each section can contain multiple pages. A page corresponds to a file in the filesystem.

Section identifers have the form:

.Page identifier
----
[section][:page]
----

=== Quest identifiers

Each

Quest identifers have the form:

.Quest identifiers
----
[section][:page][#quest]
----

=== Examples

==== Example filesystem

----
archive
├── information-security
│   └──  cryptography
│       ├── README.adoc
│       ├── symmetric-key-encryption-1.adoc
│       └── symmetric-key-encryption-2.adoc
└── mathematics
    ├── graph-theory
    │   ├── README.adoc
    │   ├── graphs-1.adoc
    │   ├── graphs-2.adoc
    │   └── lattices.adoc
    └── group-theory/
        ├── README.adoc
        ├── groups.adoc
        └── rings.adoc
----

==== Example identifiers

. `(nothing)`
** denotes directory 'archive'
. `mathematics//`
** denotes directory 'mathematics'
. `cryptography`
** denotes directory 'cryptogrphy'
. `mathematics//@`
** denotes directories 'graph-theory', and 'group-theory'
. `graph-theory:graphs-1`
** denotes file 'graphs-1.adoc'
. `graph-theory:graphs-@`
** denotes files 'graphs-1.adoc', and 'graphs-2.adoc'
. `graph-theory:@`
** denotes files 'graphs-1.adoc', 'graphs-2.adoc', 'lattices.adoc'
. `graph-theory:graphs-1#4`
** denotes the quest number '4' in the file 'graphs-1.adoc'
** it is not sure, whether it even exists
. `graph-theory:graphs-1#@`
** denotes all quest defined within 'graphs-1.adoc'
** might be none at all
. `@`
** denotes all directories within 'archive' that contain a 'README' file
. `@:@`
** denotes all files within 'archive', that are in directories together with a 'README' file
. `@:@#@`
** denotes all quests defined within the 'archive'

==== Example filesystem inspired by Zettelkasten

----
archive
└── zk
    ├── 201901231653.adoc
    ├── 201901211225.adoc
    ├── 201812231348.adoc
    └── 201812122021.adoc
----



